# ~/.config/yazi/keymap.toml

[[mgr.prepend_keymap]]
on = "e"
run = 'shell --block "$EDITOR %s"'
desc = "Open in Helix"

[[mgr.prepend_keymap]]
on = "E"
run = 'shell --block "$EDITOR"'  # 打开 Helix 但不传文件
desc = "Open Helix in current directory"
